// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9SwzP4sqm0Fv0-PCuEglHd8H_NsuDb_g',
    appId: '1:195101899668:web:d8f8d11d857c737022ad81',
    messagingSenderId: '195101899668',
    projectId: 'cibu-17d8f',
    authDomain: 'cibu-17d8f.firebaseapp.com',
    storageBucket: 'cibu-17d8f.appspot.com',
    measurementId: 'G-YFZJG0W9H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdimaGKGQ6DL9wNFl0FonJu9rZeJ5aJs8',
    appId: '1:195101899668:android:6dcc38108b60b0c322ad81',
    messagingSenderId: '195101899668',
    projectId: 'cibu-17d8f',
    storageBucket: 'cibu-17d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2U4aNoIi8VGdBT7Cy8vsr6jNwZD-wU8',
    appId: '1:195101899668:ios:716088cd7cd4b6c822ad81',
    messagingSenderId: '195101899668',
    projectId: 'cibu-17d8f',
    storageBucket: 'cibu-17d8f.appspot.com',
    iosBundleId: 'com.FMEnterprises.firstFlutterApp',
  );

}